PR #47472: [oneDNN][TSL] Add AMX_FP8 CPU feature definition and CPUID detection
Imported from GitHub PR https://github.com/openxla/xla/pull/47472

This PR is part 1 and pre-requisite for PR https://github.com/openxla/xla/pull/43318 .
The upstreamed https://github.com/openxla/xla/pull/43318 has errors. Penporn suggested to break into two, with first PR just adding the CPU feature definition and this PR just carves out the first part from PR43318.

🎯 Justification
The CI for TensorFlow uses its own pinned copy of TSL, not the one inside XLA's third_party/tsl/. Orig PR#43318 adds AMX_FP8 = 48 to XLA's local TSL copy and immediately references it in XLA code (cpu_features.cc, onednn_util.h, etc.). But when TF CI builds XLA, it resolves tsl::port::CPUFeature from its own TSL — which doesn't have AMX_FP8 yet — causing:
  error: no member named 'AMX_FP8' in 'tsl::port::CPUFeature' causing build failures.

Once this PR gets merged, PR43318 can be rebased, we won't see the CI errors.

Copybara import of the project:

--
d4d9cecfa9bd4ff858603cb41de4533b206c55d6 by Gauri Deshpande <gauri1.deshpande@intel.com>:

[TSL] Add AMX_FP8 CPU feature definition and CPUID detection

Merging this change closes #47472

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/47472 from Intel-tensorflow:gaurides/amx_fp8_cpu_info d4d9cecfa9bd4ff858603cb41de4533b206c55d6
PiperOrigin-RevId: 970436099